<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EtecSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $etecs = [
            ['codigo' => '06',  'cidade' => 'Adamantina', 'nome' => ' Engenheiro Herval Bellusci'],
            ['codigo' => '05',   'cidade' => 'Adamantina', 'nome' => ' Professor Eudécio Luiz Vicente'],
            ['codigo' => '21',   'cidade' => 'Aguaí', 'nome' => ' Arnaldo Pereira Cheregatti'],
            ['codigo' => '00',   'cidade' => 'Americana', 'nome' => ' Polivalente Etec de Americana'],
            ['codigo' => '06',   'cidade' => 'Amparo', 'nome' => ' João Belarmino'],
            ['codigo' => '028',  'cidade' => 'Andradina', 'nome' => ' Sebastiana Augusta Etec de Moraes'],
            ['codigo' => '281',  'cidade' => 'Apiaí', 'nome' => ' Etec de Apiaí'],
            ['codigo' => '165',  'cidade' => 'Araçatuba', 'nome' => ' Etec de Araçatuba'],
            ['codigo' => '029',  'cidade' => 'Araraquara', 'nome' => ' Professora Anna Etec de Oliveira Ferraz'],
            ['codigo' => '024',  'cidade' => 'Araras', 'nome' => ' Prefeito Alberto Feres'],
            ['codigo' => '274',  'cidade' => 'Arujá', 'nome' => ' Professora Luzia Maria Machado'],
            ['codigo' => '095',  'cidade' => 'Assis', 'nome' => ' Pedro D’Arcádia Neto'],
            ['codigo' => '147',  'cidade' => 'Atibaia', 'nome' => ' Professor Carmine Biagio Tundisi'],
            ['codigo' => '145',  'cidade' => 'Avaré', 'nome' => ' Professor Fausto Mazzola'],
            ['codigo' => '040',  'cidade' => 'Barra Bonita', 'nome' => ' Comendador João Rays'],
            ['codigo' => '108',  'cidade' => 'Barretos', 'nome' => ' Coronel Raphael Brandão'],
            ['codigo' => '245',  'cidade' => 'Barueri', 'nome' => ' Etec de Barueri'],
            ['codigo' => '030',  'cidade' => 'Batatais', 'nome' => ' Antonio Etec de Pádua Cardoso'],
            ['codigo' => '135',  'cidade' => 'Bauru', 'nome' => ' Rodrigues Etec de Abreu'],
            ['codigo' => '151',  'cidade' => 'Bebedouro', 'nome' => ' Professor Ídio Zucchi'],
            ['codigo' => '123',  'cidade' => 'Birigui', 'nome' => ' Doutor Renato Cordeiro'],
            ['codigo' => '051',  'cidade' => 'Botucatu', 'nome' => ' Doutor Domingos Minicucci Filho'],
            ['codigo' => '038',  'cidade' => 'Cabrália Paulista', 'nome' => ' Astor Etec de Mattos Carvalho'],
            ['codigo' => '082',  'cidade' => 'Caçapava', 'nome' => ' Machado Etec de Assis'],
            ['codigo' => '044',  'cidade' => 'Cachoeira Paulista', 'nome' => ' Professor Marcos Uchôas dos Santos Penchel'],
            ['codigo' => '062',  'cidade' => 'Cafelândia', 'nome' => ' Professora Helcy Moreira Martins Aguiar'],
            ['codigo' => '279',  'cidade' => 'Caieiras', 'nome' => ' Paulo do Carmo Monteiro'],
            ['codigo' => '191',  'cidade' => 'Cajamar', 'nome' => ' Gino Rezaghi'],
            ['codigo' => '043',  'cidade' => 'Campinas', 'nome' => ' Bento Quirino'],
            ['codigo' => '007',  'cidade' => 'Campinas', 'nome' => ' Conselheiro Antonio Prado'],
            ['codigo' => '201',  'cidade' => 'Campo Limpo Paulista', 'nome' => ' Etec de Campo Limpo Paulista'],
            ['codigo' => '081',  'cidade' => 'Cândido Mota', 'nome' => ' Professor Luiz Pires Barbosa'],
            ['codigo' => '124',  'cidade' => 'Capão Bonito', 'nome' => ' Doutor Celso Charuri'],
            ['codigo' => '213',  'cidade' => 'Caraguatatuba', 'nome' => ' Etec de Caraguatatuba'],
            ['codigo' => '144',  'cidade' => 'Carapicuíba', 'nome' => ' Etec de Carapicuíba'],
            ['codigo' => '059',  'cidade' => 'Casa Branca', 'nome' => ' Doutor Francisco Nogueira Etec de Lima'],
            ['codigo' => '054',  'cidade' => 'Catanduva', 'nome' => ' Elias Nechar'],
            ['codigo' => '072',  'cidade' => 'Cerqueira Cesar', 'nome' => ' Prefeito José Esteves'],
            ['codigo' => '248',  'cidade' => 'Cerquilho', 'nome' => ' Etec de Cerquilho'],
            ['codigo' => '222',  'cidade' => 'Cotia', 'nome' => ' Etec de Cotia'],
            ['codigo' => '077',  'cidade' => 'Cruzeiro', 'nome' => ' Professor José Sant’Ana Etec de Castro'],
            ['codigo' => '181',  'cidade' => 'Cubatão', 'nome' => ' Etec de Cubatão'],
            ['codigo' => '166',  'cidade' => 'Diadema', 'nome' => ' Juscelino Kubitschek Etec de Oliveira'],
            ['codigo' => '052',  'cidade' => 'Dracena', 'nome' => ' Professora Carmelina Barbosa'],
            ['codigo' => '241',  'cidade' => 'Embu das Artes', 'nome' => ' Etec de Embu'],
            ['codigo' => '047',  'cidade' => 'Espírito Santo do Pinhal', 'nome' => ' Doutor Carolino da Motta e Silva'],
            ['codigo' => '138',  'cidade' => 'Fernandópolis', 'nome' => ' Professor Armando José Farinazzo'],
            ['codigo' => '170',  'cidade' => 'Ferraz Etec de Vasconcelos', 'nome' => ' Etec de Ferraz Etec de Vasconcelos'],
            ['codigo' => '078',  'cidade' => 'Franca', 'nome' => ' Doutor Júlio Cardoso'],
            ['codigo' => '046',  'cidade' => 'Franca', 'nome' => ' Professor Carmelino Correa Júnior'],
            ['codigo' => '231',  'cidade' => 'Francisco Morato', 'nome' => ' Etec de Francisco Morato'],
            ['codigo' => '142',  'cidade' => 'Franco da Rocha', 'nome' => ' Doutor Emílio Hernandez Aguilar'],
            ['codigo' => '093',  'cidade' => 'Garça', 'nome' => ' Deputado Paulo Ornellas Carvalho Etec de Barros'],
            ['codigo' => '088',  'cidade' => 'Garça', 'nome' => ' Monsenhor Antônio Magliano'],
            ['codigo' => '026',  'cidade' => 'Guaratinguetá', 'nome' => ' Professor Alfredo Etec de Barros Santos'],
            ['codigo' => '256',  'cidade' => 'Guariba', 'nome' => ' Bento Carlos Botelho do Amaral'],
            ['codigo' => '152',  'cidade' => 'Guarujá', 'nome' => ' Alberto Santos Dumont'],
            ['codigo' => '295',  'cidade' => 'Guarulhos', 'nome' => ' Etec de Guarulhos'],
            ['codigo' => '115',  'cidade' => 'Hortolândia', 'nome' => ' Etec de Hortolândia'],
            ['codigo' => '263',  'cidade' => 'Ibaté', 'nome' => ' Etec de Ibaté'],
            ['codigo' => '161',  'cidade' => 'Ibitinga', 'nome' => ' Vereador e Vice Prefeito Sérgio da Fonseca'],
            ['codigo' => '033',  'cidade' => 'Igarapava', 'nome' => ' Antonio Junqueira da Veiga'],
            ['codigo' => '089',  'cidade' => 'Iguape', 'nome' => ' Engenheiro Agrônomo Narciso Etec de Medeiros'],
            ['codigo' => '065',  'cidade' => 'Ilha Solteira', 'nome' => ' Etec de Ilha Solteira'],
            ['codigo' => '097',  'cidade' => 'Ipaussu', 'nome' => ' Professor Pedro Leme Brisolla Sobrinho'],
            ['codigo' => '158',  'cidade' => 'Itanhaém', 'nome' => ' Etec de Itanhaém'],
            ['codigo' => '261',  'cidade' => 'Itapetininga', 'nome' => ' Darcy Pereira Etec de Moraes'],
            ['codigo' => '053',  'cidade' => 'Itapetininga', 'nome' => ' Professor Edson Galvão'],
            ['codigo' => '050',  'cidade' => 'Itapeva', 'nome' => ' Doutor Demétrio Azevedo Júnior'],
            ['codigo' => '218',  'cidade' => 'Itapira', 'nome' => ' João Maria Stevanatto'],
            ['codigo' => '249',  'cidade' => 'Itaquaquecetuba', 'nome' => ' Etec de Itaquaquecetuba'],
            ['codigo' => '243',  'cidade' => 'Itararé', 'nome' => ' Etec de Itararé'],
            ['codigo' => '100',  'cidade' => 'Itatiba', 'nome' => ' Rosa Perrone Scavone'],
            ['codigo' => '086',  'cidade' => 'Itu', 'nome' => ' Martinho Di Ciero'],
            ['codigo' => '233',  'cidade' => 'Ituverava', 'nome' => ' Professor José Ignácio Azevedo Filho'],
            ['codigo' => '048',  'cidade' => 'Jacareí', 'nome' => ' Cônego José Bento'],
            ['codigo' => '073',  'cidade' => 'Jales', 'nome' => ' Doutor José Luiz Viana Coutinho'],
            ['codigo' => '268',  'cidade' => 'Jandira', 'nome' => ' Prefeito Braz Paschoalin'],
            ['codigo' => '070',  'cidade' => 'Jaú', 'nome' => ' Joaquim Ferreira do Amaral'],
            ['codigo' => '090',  'cidade' => 'Jaú', 'nome' => ' Professor Urias Ferreira'],
            ['codigo' => '042',  'cidade' => 'Jundiaí', 'nome' => ' Benedito Storani'],
            ['codigo' => '008',  'cidade' => 'Jundiaí', 'nome' => ' Vasco Antonio Venchiarutti'],
            ['codigo' => '110',  'cidade' => 'Leme', 'nome' => ' Deputado Salim Sedeh'],
            ['codigo' => '244',  'cidade' => 'Lençóis Paulista', 'nome' => ' Cidade do Livro'],
            ['codigo' => '104',  'cidade' => 'Limeira', 'nome' => ' Trajano Camargo'],
            ['codigo' => '148',  'cidade' => 'Lins', 'nome' => ' Etec de Lins'],
            ['codigo' => '240',  'cidade' => 'Lorena', 'nome' => ' Padre Carlos Leôncio da Silva'],
            ['codigo' => '235',  'cidade' => 'Mairinque', 'nome' => ' Etec de Mairinque'],
            ['codigo' => '271',  'cidade' => 'Mairiporã', 'nome' => ' Etec de Mairiporã'],
            ['codigo' => '031',  'cidade' => 'Marília', 'nome' => ' Antonio Devisate'],
            ['codigo' => '103',  'cidade' => 'Matão', 'nome' => ' Sylvio Etec de Mattos Carvalho'],
            ['codigo' => '128',  'cidade' => 'Mauá', 'nome' => ' Etec de Mauá'],
            ['codigo' => '079',  'cidade' => 'Miguelópolis', 'nome' => ' Laurindo Alves Etec de Queiroz'],
            ['codigo' => '087',  'cidade' => 'Mirassol', 'nome' => ' Professor Matheus Leite Etec de Abreu'],
            ['codigo' => '060',  'cidade' => 'Mococa', 'nome' => ' Francisco Garcia'],
            ['codigo' => '009',  'cidade' => 'Mococa', 'nome' => ' João Baptista Etec de Lima Figueiredo'],
            ['codigo' => '015',  'cidade' => 'Mogi das Cruzes', 'nome' => ' Presidente Vargas'],
            ['codigo' => '206',  'cidade' => 'Mogi Guaçu', 'nome' => ' Euro Albino Etec de Souza'],
            ['codigo' => '096',  'cidade' => 'Mogi Mirim', 'nome' => ' Pedro Ferreira Alves'],
            ['codigo' => '107',  'cidade' => 'Mongaguá', 'nome' => ' Adolpho Berezin'],
            ['codigo' => '255',  'cidade' => 'Monte Alto', 'nome' => ' Alcides Cestari'],
            ['codigo' => '075',  'cidade' => 'Monte Aprazível', 'nome' => ' Padre José Nunes Dias'],
            ['codigo' => '198',  'cidade' => 'Monte Mor', 'nome' => ' Etec de Monte Mor'],
            ['codigo' => '234',  'cidade' => 'Nova Odessa', 'nome' => ' Ferrucio Humberto Gazzetta'],
            ['codigo' => '212',  'cidade' => 'Novo Horizonte', 'nome' => ' Professora Marinês Teodoro Etec de Freitas Almeida'],
            ['codigo' => '232',  'cidade' => 'Olímpia', 'nome' => ' Professor José Carlos Seno Junior'],
            ['codigo' => '025',  'cidade' => 'Orlândia', 'nome' => ' Professor Alcídio Etec de Souza Prado'],
            ['codigo' => '242',  'cidade' => 'Osasco', 'nome' => ' Dr. Celso Giglio'],
            ['codigo' => '149',  'cidade' => 'Osasco', 'nome' => ' Professor André Bogasian'],
            ['codigo' => '027',  'cidade' => 'Osvaldo Cruz', 'nome' => ' Amim Jundi'],
            ['codigo' => '066',  'cidade' => 'Ourinhos', 'nome' => ' Jacinto Ferreira Etec de Sá'],
            ['codigo' => '164',  'cidade' => 'Palmital', 'nome' => ' Professor Mário Antônio Verza'],
            ['codigo' => '039',  'cidade' => 'Paraguaçu Paulista', 'nome' => ' Augusto Tortolero Araújo'],
            ['codigo' => '069',  'cidade' => 'Penápolis', 'nome' => ' João Jorge Geraissate'],
            ['codigo' => '266',  'cidade' => 'Peruíbe', 'nome' => ' Etec de Peruíbe'],
            ['codigo' => '203',  'cidade' => 'Piedade', 'nome' => ' Etec de Piedade'],
            ['codigo' => '068',  'cidade' => 'Pindamonhangaba', 'nome' => ' João Gomes Etec de Araújo'],
            ['codigo' => '056',  'cidade' => 'Piracicaba', 'nome' => ' Coronel Fernando Febeliano da Costa'],
            ['codigo' => '193',  'cidade' => 'Piracicaba', 'nome' => ' Deputado Ary Etec de Camargo Pedroso'],
            ['codigo' => '162',  'cidade' => 'Piraju', 'nome' => ' Waldyr Duron Junior'],
            ['codigo' => '139',  'cidade' => 'Pirassununga', 'nome' => ' Tenente Aviador Gustavo Klug'],
            ['codigo' => '210',  'cidade' => 'Poá', 'nome' => ' Etec de Poá'],
            ['codigo' => '289',  'cidade' => 'Porto Feliz', 'nome' => ' Etec de Porto Feliz'],
            ['codigo' => '202',  'cidade' => 'Porto Ferreira', 'nome' => ' Professor Jadyr Salles'],
            ['codigo' => '153',  'cidade' => 'Praia Grande', 'nome' => ' Etec de Praia Grande'],
            ['codigo' => '252',  'cidade' => 'Presidente Prudente', 'nome' => ' Professor Adolpho Arruda Mello'],
            ['codigo' => '032',  'cidade' => 'Presidente Prudente', 'nome' => ' Professor Doutor Antonio Eufrásio Toledo'],
            ['codigo' => '099',  'cidade' => 'Presidente Venceslau', 'nome' => ' Professor Milton Gazzetti'],
            ['codigo' => '080',  'cidade' => 'Quatá', 'nome' => ' Doutor Luiz Cesar Couto'],
            ['codigo' => '058',  'cidade' => 'Rancharia', 'nome' => ' Deputado Francisco Franco'],
            ['codigo' => '239',  'cidade' => 'Registro', 'nome' => ' Etec de Registro'],
            ['codigo' => '141',  'cidade' => 'Ribeirão Pires', 'nome' => ' Professora Maria Cristina Medeiros'],
            ['codigo' => '074',  'cidade' => 'Ribeirão Preto', 'nome' => ' José Martimiano da Silva'],
            ['codigo' => '036',  'cidade' => 'Rio Claro', 'nome' => ' Professor Armando Bayeux da Silva'],
            ['codigo' => '071',  'cidade' => 'Rio das Pedras', 'nome' => ' Doutor José Coury'],
            ['codigo' => '282',  'cidade' => 'Rio Grande da Serra', 'nome' => ' Etec de Rio Grande da Serra'],
            ['codigo' => '117',  'cidade' => 'Santa Bárbara d’Oeste', 'nome' => ' Professor Doutor José Dagnoni'],
            ['codigo' => '287',  'cidade' => 'Santa Cruz das Palmeiras', 'nome' => ' João Elias Margutti'],
            ['codigo' => '084',  'cidade' => 'Santa Cruz do Rio Pardo', 'nome' => ' Orlando Quagliato'],
            ['codigo' => '277',  'cidade' => 'Santa Fé do Sul', 'nome' => ' Etec de Santa Fé do Sul'],
            ['codigo' => '219',  'cidade' => 'Santa Isabel', 'nome' => ' Etec de Santa Isabel'],
            ['codigo' => '083',  'cidade' => 'Santa Rita do Passa Quatro', 'nome' => ' Manoel dos Reis Araújo'],
            ['codigo' => '237',  'cidade' => 'Santa Rosa Etec de Viterbo', 'nome' => ' Etec de Santa Rosa Etec de Viterbo'],
            ['codigo' => '262',  'cidade' => 'Santana Etec de Parnaíba', 'nome' => ' Bartolomeu Bueno da Silva – Anhanguera'],
            ['codigo' => '187',  'cidade' => 'Santana Etec de Parnaíba', 'nome' => ' Professora Ermelinda Giannini Teixeira'],
            ['codigo' => '014',  'cidade' => 'Santo André', 'nome' => ' Júlio Etec de Mesquita'],
            ['codigo' => '035',  'cidade' => 'Santos', 'nome' => ' Aristóteles Ferreira'],
            ['codigo' => '122',  'cidade' => 'Santos', 'nome' => ' Dona Escolástica Rosa'],
            ['codigo' => '010',  'cidade' => 'São Bernardo do Campo', 'nome' => ' Lauro Gomes'],
            ['codigo' => '011',  'cidade' => 'São Caetano do Sul', 'nome' => ' Jorge Street'],
            ['codigo' => '091',  'cidade' => 'São Carlos', 'nome' => ' Paulino Botelho'],
            ['codigo' => '094',  'cidade' => 'São Joaquim da Barra', 'nome' => ' Pedro Badran'],
            ['codigo' => '150',  'cidade' => 'São José do Rio Pardo', 'nome' => ' Professor Rodolpho José Del Guerra'],
            ['codigo' => '098',  'cidade' => 'São José do Rio Preto', 'nome' => ' Philadelpho Gouvea Netto'],
            ['codigo' => '195',  'cidade' => 'São José dos Campos', 'nome' => ' Professora Ilza Nascimento Pintus'],
            ['codigo' => '102',  'cidade' => 'São Manuel', 'nome' => ' Dona Sebastiana Etec de Barros'],
            ['codigo' => '224',  'cidade' => 'São Paulo', 'nome' => 'Abdias do Nascimento'],
            ['codigo' => '023',  'cidade' => 'São Paulo', 'nome' => 'Albert Einstein'],
            ['codigo' => '045',  'cidade' => 'São Paulo', 'nome' => 'Carlos Etec de Campos'],
            ['codigo' => '134',  'cidade' => 'São Paulo', 'nome' => 'Carolina Carinhato Sampaio'],
            ['codigo' => '223',  'cidade' => 'São Paulo', 'nome' => 'Cepam'],
            ['codigo' => '180',  'cidade' => 'São Paulo', 'nome' => 'Etec de Artes'],
            ['codigo' => '199',  'cidade' => 'São Paulo', 'nome' => 'Etec de Cidade Tiradentes'],
            ['codigo' => '267',  'cidade' => 'São Paulo', 'nome' => 'Etec de Esportes Curt Walter Otto Baumgart'],
            ['codigo' => '118',  'cidade' => 'São Paulo', 'nome' => ' Etec de Guaianazes'],
            ['codigo' => '205',  'cidade' => 'São Paulo', 'nome' => ' Etec de Heliópolis'],
            ['codigo' => '169',  'cidade' => 'São Paulo', 'nome' => ' Etec de Itaquera'],
            ['codigo' => '018',  'cidade' => 'São Paulo', 'nome' => ' Etec de São Paulo'],
            ['codigo' => '172',  'cidade' => 'São Paulo', 'nome' => ' Etec de Sapopemba'],
            ['codigo' => '208',  'cidade' => 'São Paulo', 'nome' => ' Etec de Tiquatira'],
            ['codigo' => '185',  'cidade' => 'São Paulo', 'nome' => ' Etec de Vila Formosa'],
            ['codigo' => '154',  'cidade' => 'São Paulo', 'nome' => ' Doutora Maria Augusta Saraiva'],
            ['codigo' => '013',  'cidade' => 'São Paulo', 'nome' => ' Getúlio Vargas'],
            ['codigo' => '226',  'cidade' => 'São Paulo', 'nome' => ' Gildo Marçal Bezerra Brandão'],
            ['codigo' => '061',  'cidade' => 'São Paulo', 'nome' => ' Guaracy Silveira'],
            ['codigo' => '238',  'cidade' => 'São Paulo', 'nome' => ' Irmã Agostina'],
            ['codigo' => '285',  'cidade' => 'São Paulo', 'nome' => ' Itaquera II'],
            ['codigo' => '228',  'cidade' => 'São Paulo', 'nome' => ' Jaraguá'],
            ['codigo' => '221',  'cidade' => 'São Paulo', 'nome' => ' Jardim  ngela'],
            ['codigo' => '253',  'cidade' => 'São Paulo', 'nome' => ' Jornalista Roberto Marinho'],
            ['codigo' => '076',  'cidade' => 'São Paulo', 'nome' => ' José Rocha Mendes'],
            ['codigo' => '247',  'cidade' => 'São Paulo', 'nome' => ' Mandaqui'],
            ['codigo' => '085',  'cidade' => 'São Paulo', 'nome' => ' Martin Luther King'],
            ['codigo' => '220',  'cidade' => 'São Paulo', 'nome' => ' Parque Belém'],
            ['codigo' => '159',  'cidade' => 'São Paulo', 'nome' => ' Parque da Juventude'],
            ['codigo' => '229',  'cidade' => 'São Paulo', 'nome' => ' Paulistano'],
            ['codigo' => '207',  'cidade' => 'São Paulo', 'nome' => ' Professor Adhemar Batista Heméritas'],
            ['codigo' => '034',  'cidade' => 'São Paulo', 'nome' => ' Professor Aprígio Gonzaga'],
            ['codigo' => '041',  'cidade' => 'São Paulo', 'nome' => ' Professor Basílides Etec de Godoy'],
            ['codigo' => '012',  'cidade' => 'São Paulo', 'nome' => ' Professor Camargo Aranha'],
            ['codigo' => '06',   'cidade' => 'São Paulo', 'nome' => ' Professor Horácio Augusto da Silveira'],
            ['codigo' => '25',   'cidade' => 'São Paulo', 'nome' => ' Professora Doutora Doroti Quiomi Kanashiro Toyohara'],
            ['codigo' => '22',   'cidade' => 'São Paulo', 'nome' => ' Raposo Tavares'],
            ['codigo' => '26',   'cidade' => 'São Paulo', 'nome' => ' Santa Ifigênia'],
            ['codigo' => '22',   'cidade' => 'São Paulo', 'nome' => ' São Mateus'],
            ['codigo' => '27',   'cidade' => 'São Paulo', 'nome' => ' Sebrae'],
            ['codigo' => '200',  'cidade' => 'São Paulo', 'nome' => ' Takashi Morita'],
            ['codigo' => '186',  'cidade' => 'São Paulo', 'nome' => ' Tereza Aparecida Cardoso Nunes Etec de Oliveira'],
            ['codigo' => '230',  'cidade' => 'São Paulo', 'nome' => ' Uirapuru'],
            ['codigo' => '211',  'cidade' => 'São Paulo', 'nome' => ' Zona Leste'],
            ['codigo' => '236',  'cidade' => 'São Pedro', 'nome' => ' Gustavo Teixeira'],
            ['codigo' => '116',  'cidade' => 'São Roque', 'nome' => ' Etec de São Roque'],
            ['codigo' => '188',  'cidade' => 'São Sebastião', 'nome' => ' Etec de São Sebastião'],
            ['codigo' => '057',  'cidade' => 'São Simão', 'nome' => ' Professor Francisco dos Santos'],
            ['codigo' => '194',  'cidade' => 'São Vicente', 'nome' => ' Doutora Ruth Cardoso'],
            ['codigo' => '214',  'cidade' => 'Serrana', 'nome' => '  ngelo Cavalheiro'],
            ['codigo' => '264',  'cidade' => 'Sorocaba', 'nome' => ' Armando Pannunzio'],
            ['codigo' => '016',  'cidade' => 'Sorocaba', 'nome' => ' Fernando Prestes'],
            ['codigo' => '017',  'cidade' => 'Sorocaba', 'nome' => ' Rubens Etec de Faria e Souza'],
            ['codigo' => '190',  'cidade' => 'Suzano', 'nome' => ' Etec de Suzano'],
            ['codigo' => '293',  'cidade' => 'Taboão da Serra', 'nome' => ' Etec de Taboão da Serra'],
            ['codigo' => '019',  'cidade' => 'Taquaritinga', 'nome' => ' Doutor Adail Nunes da Silva'],
            ['codigo' => '140',  'cidade' => 'Taquarituba', 'nome' => ' Professora Terezinha Monteiro dos Santos'],
            ['codigo' => '049',  'cidade' => 'Taquarivaí', 'nome' => ' Doutor Dário Pacheco Pedroso'],
            ['codigo' => '101',  'cidade' => 'Tatuí', 'nome' => ' Sales Gomes'],
            ['codigo' => '125',  'cidade' => 'Taubaté', 'nome' => ' Doutor Geraldo José Rodrigues Alckmin'],
            ['codigo' => '156',  'cidade' => 'Teodoro Sampaio', 'nome' => ' Professora Nair Luccas Ribeiro'],
            ['codigo' => '246',  'cidade' => 'Tietê', 'nome' => ' Doutor Nelson Alves Vianna'],
            ['codigo' => '136',  'cidade' => 'Tupã', 'nome' => ' Professor Massuyuki Kawano'],
            ['codigo' => '179',  'cidade' => 'Vargem Grande do Sul', 'nome' => ' Etec de Vargem Grande do Sul'],
            ['codigo' => '092',  'cidade' => 'Vera Cruz', 'nome' => ' Paulo Guerreiro Franco'],
            ['codigo' => '197',  'cidade' => 'Votorantim', 'nome' => ' Professor Elias Miguel Júnior'],
            ['codigo' => '037',  'cidade' => 'Votuporanga', 'nome' => ' Frei Arnaldo Maria Etec de Itaporanga']
        ];

        foreach ($etecs as $etec) 
            $this->insere_dados($etec);
        
    }

     function insere_dados($etec){
        DB::table('etecs')->insert([
            'nome'   => $etec['nome'],
            'codigo' => $etec['codigo'],
            'cidade' => $etec['cidade']
        ]);
    }
    
}

    

  
